name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  #   paths_ignore:
  #     - 'kubernetes/deployment.yaml' # Ignore changes to this file to prevent loops

  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
     
      - name: Install dependencies
        run: npm ci
     
      - name: Run tests
        run: npm test || echo "No tests found, would tests in real world project"


  lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
     
      - name: Install dependencies
        run: npm ci

      - name: Run ESlint
        run: npm run lint
      
    
